### PR TITLE
Add Spanish version of CONTRIBUTING.adoc file

### PR DESCRIPTION
**Pull request by emecas**
Related to [#626](https://github.com/eclipse/microprofile-marketing/issues/626)
 
Signed-off-by: Emerson Castaneda <emecas@users.noreply.github.com>

### CODE REVIEW

**Review by aeiras — APPROVED** [review]
Looks wonderful, Emerson! 

Thank you for caring to support the translation into Spanish. Your actions are beautiful!

**Comment by aeiras** [comment]
Emerson, 

Do you wish to add the new doc into the English Version as well? 

https://github.com/emecas/microprofile/blob/contributing_es/CONTRIBUTING.adoc

The English version is linked in the website under Contributing call to action "Become A MicroProfiler" https://microprofile.io/contributors/

What is your take on this?

**Comment by aeiras** [comment]
Emerson, 

Do you wish to add the new doc into the English Version as well? 

https://github.com/emecas/microprofile/blob/contributing_es/CONTRIBUTING.adoc

The English version is linked in the website under Contributing call to action "Become A MicroProfiler" https://microprofile.io/contributors/

What is your take on this?

**Comment by emecas** [comment]
> Emerson,
> 
> Do you wish to add the new doc into the English Version as well?
> 
> https://github.com/emecas/microprofile/blob/contributing_es/CONTRIBUTING.adoc
> 
> The English version is linked in the website under Contributing call to action "Become A MicroProfiler" https://microprofile.io/contributors/
> 
> What is your take on this?

ahhh OK OK , I see what you meant now, you referred tot mix both, English and Spanish, in a single page, yes, I can do that, for this PR I had visualized  adding  the ES translation as a new page: https://github.com/eclipse/microprofile/blob/master/CONTRIBUTING_es.adoc, but we can change it to the suggested approach, all text in one place.

**Pull request merged**
