### PR TITLE
Mark dependencies as 'provided' scope

### PR DESCRIPTION
**Pull request by ederks85**
- Mark dependencies as 'provided' scope
- Fixed platform dependent encoding warning by explicitly setting encoding to UTF-8

Signed-off-by: Edwin Derks <ederks85@gmail.com>

### CODE REVIEW

**Comment by ederks85** [comment]
DECISION: All specifications must move to provided scope dependencies in order to be included in 4.0.

If this is properly set up for every MP component, whether by explicitly checking this in PR review, or maybe with the maven-enforcer-plugin, this should prevent the issue you are describing.

This way, whenever an arbitrary project includes a MP component dependency directly OR transitively via the MP platform 4.0 dependency, the result should be that the MP component API artifact is NOT showing up in the final Maven artifact.

Do let me know if I have misunderstood your comment

**Comment by ederks85** [comment]
Ah yes, the component specs also must then define the included API's as 'provided' since otherwise, these would be included in the final build artifiact if you include a MP component directly. The puzzle is starting to make sense in my head again :)

**Comment by jclingan** [comment]
so I'm confused here as to what to do. We can do it in the platform spec, but given the short time, I don't want to put this on component specs. We have two choices: Push at platform spec and require component specs to add before next Milestone/CR build, or hold on the platform spec and do them all at once. Preference?

**Comment by kenfinnigan** [comment]
I believe all specifications were modified to have "provided" scope for Jakarta dependencies earlier this year

**Comment by ederks85** [comment]
@kenfinnigan if that's the case, then there is no problem and we can merge the platform spec. This is how the Maven dependency output looks with the platform spec changes:

`[INFO] org.eclipse.microprofile:microprofile-spec:pom:4.0-SNAPSHOT
[INFO] +- javax.enterprise:cdi-api:jar:2.0:provided
[INFO] |  +- javax.el:javax.el-api:jar:3.0.0:provided
[INFO] |  +- javax.interceptor:javax.interceptor-api:jar:1.2:provided
[INFO] |  \- javax.inject:javax.inject:jar:1:provided
[INFO] +- javax.ws.rs:javax.ws.rs-api:jar:2.1:provided
[INFO] +- javax.json.bind:javax.json.bind-api:jar:1.0:provided
[INFO] +- javax.json:javax.json-api:jar:1.1:provided
[INFO] +- javax.annotation:javax.annotation-api:jar:1.3:provided
[INFO] +- org.eclipse.microprofile.config:microprofile-config-api:jar:1.4:provided
[INFO] +- org.eclipse.microprofile.fault-tolerance:microprofile-fault-tolerance-api:jar:2.1:provided
[INFO] |  \- org.osgi:org.osgi.annotation.versioning:jar:1.0.0:provided
[INFO] +- org.eclipse.microprofile.health:microprofile-health-api:jar:2.2:provided
[INFO] +- org.eclipse.microprofile.metrics:microprofile-metrics-api:jar:2.3:provided
[INFO] +- org.eclipse.microprofile.jwt:microprofile-jwt-auth-api:jar:1.1:provided
[INFO] +- org.eclipse.microprofile.openapi:microprofile-openapi-api:jar:1.1:provided
[INFO] +- org.eclipse.microprofile.rest.client:microprofile-rest-client-api:jar:1.4.0:provided
[INFO] \- org.eclipse.microprofile.opentracing:microprofile-opentracing-api:jar:1.3:provided`

We can send a message on the mailing list with the request for every specification to check if the `javax.*` and `org.eclipse.microprofile.*` dependencies are on provided scope

The sooner we can do this, the more time we have to revert these changes if we find that we have overlooked something. If you agree, I can send out the mail if you like

**Comment by jclingan** [comment]
Edwin, you wanna send out the message?

**Comment by ederks85** [comment]
Done, I have piggybacked on the 'Help with MicroProfile 4.0 M1' thread that already addressed the spec teams for support on MP 4.0 M1

**Comment by jclingan** [comment]
Thanks!

**Pull request merged**
