### PR TITLE
added BOM for MP 2.1

### PR DESCRIPTION
**Pull request by sdaschner**
Added a first draft of an updated MP BOM using version 2.1

### CODE REVIEW

**Comment by kenfinnigan** [comment]
@sdaschner I'm not sure these should be added to the `attic` folder as I believe that's an archive of older things. @kwsutter can correct me there.

Also, do you have a ECA signed as it's failing because it thinks you don't have one

**Comment by sdaschner** [comment]
@kenfinnigan Yes, I'm pretty sure that isn't the correct place to be in. Just wanted to add it somewhere; please feel free to take / modify / relocate, or to tell me how to proceed :)

**Comment by sdaschner** [comment]
Updated with the ECA sign-off

**Comment by kenfinnigan** [comment]
@kwsutter any view on the correct place for these files, as I don't think the attic is right

**Comment by kwsutter** [comment]
Sorry, I missed this!  We never did take the time to properly define a BOM for MicroProfile.  Thus, we decided the release mechanism would be done in this repo and any future work on a real BOM would be done in [here](https://github.com/eclipse/microprofile-bom).  @sdaschner, you already found the conversation in the forum.  So, you know the history.  The "attic" in this repo was the old stuff that could be resurrected, if necessary.  But, not in this repo.  It should be done in the microprofile-bom repo.  Thanks!

**Comment by kwsutter** [comment]
Just noticed that PR #84 is proposing a similar change, except in the main pom.xml file...  Are there any drawbacks with going with this dependency management concept?  At one time, it seemed that we wanted to separate the Spec/API platform pom from the BOM idea.  But, if this approach would help with the acceptance and usage of the platform pom, then I'm willing to entertain it.  Thanks.

**Comment by sdaschner** [comment]
Already fixed in `2.2` by another PR.

**Pull request closed without merging**
