### PR TITLE
Import bom repository

### PR DESCRIPTION
**Pull request by OndrejM**
Imported microprofile-bom repository contents into the `microprofile-spec` folder, with history preserved using git rebase.

### CODE REVIEW

**Comment by OndrejM** [comment]
@kwsutter I rebased all commits from the bom repo. It seems that the IP validator doesn't like it as those commits were not mine. I think we can safely ignore the IP check, as the code already passed IP checks in the bom repo, what do you think? 
Otherwise we would have to copy the content without the history as there's no way how a single user could create a PR with commits from multiple people.

**Comment by kwsutter** [comment]
I also agree that we could safely ignore the IP Validation "errors" since all of the proposed changes had already been validated in the microprofile-bom repo.

**Comment by OndrejM** [comment]
@kwsutter I already rebased on https://github.com/eclipse/microprofile/pull/24 because I expected it will be merged soon ;-) 

The bom repo stays, I just copied the commits to this repo. We can do whatever we want with the bom repo. I suggest deleting everything with a single commit (except meta files like license) and create a BOM maven project from scratch. The history of MP spec will therefore stay in the bom repo but is replicated in this repo for convenience.

**Comment by kwsutter** [comment]
@OndrejM I'm assuming that your proposed microprofile-spec directory is just a temporary placeholder to get the material over here?  I believe that our automated build processes (jenkins) expects the spec/api/tck format.  And, we'll have to adjust the top-level pom, etc.  Just wanted to verify that we were in sync on this.  Also, once this re-org is done, should we re-create the github Release tags for the current MicroProfile releases?

**Comment by OndrejM** [comment]
Hi @kwsutter, I moved it to a subfolder because putting it to the root would conflict with the existing README in this repo. Should I try merging the 2 different README files into one and move all files to the root?

**Comment by kwsutter** [comment]
@OndrejM I think it's okay to make this initial move as-is and then adjust after the fact, don't you think?  Once we get the parts over into this component, then we are free to move them around as we need to.  Let's do it that way.  It's clearer on the initial move, followed by additional cleanup.

**Comment by OndrejM** [comment]
@kwsutter if it's OK, please merge this PR. I agree that we can reorganize contents later if automated builds need it.

**Pull request merged**
