### PR TITLE
Add MP Health 2.0 to MP 3.0 release

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang@uk.ibm.com>

### CODE REVIEW

**Comment by antoinesd** [comment]
@Emily-Jiang will you finish this PR for today or should I add the missing commits to it?

**Comment by kwsutter** [comment]
Yes, we do need the asciidoc updates as well.  Please and Thank You.  :-)  
It also looks like @Emily-Jiang used the wrong github userid for creating the PR since it didn't pass the Eclipse ECA check...

Let me know when it's ready to review and merge.  Thanks!

**Comment by antoinesd** [comment]
Ok, for the record I'm starting a new PR for this

**Comment by Emily-Jiang** [comment]
Not sure what happened. I have been used my IBM note id to do the commit. Suddenly it failed ECA check. I'll look into it.

**Comment by antoinesd** [comment]
Sent another PR: #114

**Pull request closed without merging**
